### ISSUE TITLE
Metadata for Fellows Page

### ISSUE THREAD

**Issue by mvdanilova** [GSA/digitalcorps.gsa.gov#127]
Fellow per row
Hometown
Work Location
Year
Bio
Why USDC

**Comment by chriskuang4** [comment]
Data fields and content is here: https://docs.google.com/spreadsheets/d/1eTmC1cHCjSbTC7SG0bf7Te9WLG99XV8IqfbiBuK2vIg/edit#gid=0

@Dahianna is leading in the collection of information as well as curating the responses for gallery view.
