### ISSUE TITLE
Tabbing highlights missing in some places

### ISSUE THREAD

**Issue by DaveSkender** [GSA/digitalcorps.gsa.gov#133]
## Describe the bug

When tabbing through the homepage, clickable elements are highlighted with a consistent thick blue border for visually impaired persons.  The two clickable cards (below) do not highlight when they receive focus.

I suspect this highlight may also be missing on the track "bubble" navigation icons (not currently shown on site / out of season).

## To Reproduce

1. Do a fresh reload of the home page without clicking anywhere
2. Use the keyboard Tab key to navigate through the controls until you get to these cards
3. Observe that they do not highlight as expected

## Expected behavior

It is probably sufficient to have the same effect as is currently on mouse "hover" when tab focus is achieved, though there may also be an existing USWDS style treatment that includes a small amount of object padding that would be better.

## Screenshots or other reference materials

![image](https://user-images.githubusercontent.com/8432125/173158946-24f2cb39-b61c-47f9-a8f5-6559f94b8548.png)

**Comment by chriskuang4** [comment]
Jared will get to this when we circle back to AMP testing for 2023.

**Comment by chriskuang4** [comment]
Jared working on this now.
