### ISSUE TITLE
Edits/additions to Fellow & agency pages

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#181]
- [x] Add EPA as a host agency and add to Dhan + Olivia's pages (as soon as ready)
- [x] Add CMS to Karley's page (Mon 7 /25)
- [x] Add GSA to John R's page (as soon as ready)

**Comment by chriskuang4** [comment]
@jaredbain upon further review -- we are ready to add the EPA pieces today/as soon as ready as well.

**Comment by jaredbain** [comment]
@chriskuang4  Okay so its just CMS that needs to wait until Mon(7/25)?
