### ISSUE TITLE
Replace Fellow photos with GSA headshots

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#186]
Probably makes the most sense to update all at once, when all Fellows have received their GSA headshots. Currently, only non-DC Fellows have sat for photos (none have been received from OSC).

Revisit in January 2023

**Comment by chriskuang4** [comment]
@Dahianna Sahithi mentioned being willing to do headshots for local Fellows. Can you please forward me the latest email chain with OSC so I can follow up about potentially getting access to their studio?

**Comment by Dahianna** [comment]
Waiting on headshots from the following Fellows:
- Anastasia
- Chizo
- Christy
- Jasmine
- Jay
- John
- Julie
- Kathleen
- Liane
- Olivia
- Pierce
- Sahithi
- Samira
- Thomas

Also,  Nina asked to keep her current photo

**Comment by chriskuang4** [comment]
We need to resize images for web, reformat TIF file into JPG/PNG

**Comment by chriskuang4** [comment]
Folder with photos: https://drive.google.com/drive/folders/1R90hhR_8OCNnEU7l-E_hqPyOacyvgGn7

**Comment by chriskuang4** [comment]
@jaredbain to start a branch, @danielaaburtotc taking the lead on formatting/resizing, @Dahianna tracking down stragglers to confirm preference of GSA photo or old photo.

**Comment by chriskuang4** [comment]
We are tracking updates in this spreadsheet: https://docs.google.com/spreadsheets/d/1Rf86AnTCFb7EWADJpgTS32caObzrk6zYaR-pJQV9hZk/edit#gid=657350050
