### ISSUE TITLE
Replace stock photos with orientation photos

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#191]
- [ ] @danielaaburtotc is formatting photos (4 remaining to send to Jared)
- [ ] @Dahianna to get Fellow approvals (anything outside whole group shots)
- [ ] @jaredbain to add to website

[Spreadsheet with photos and locations](https://docs.google.com/spreadsheets/d/1Rf86AnTCFb7EWADJpgTS32caObzrk6zYaR-pJQV9hZk/edit#gid=0)

Estimated Completion: 1 day

**Comment by jaredbain** [comment]
Home Page - US Government block (find new photo)
Opportunity Page Banner - (Waiting on new exported photo)
Application Process Banner - (Find new photo)

**Comment by jaredbain** [comment]
Update Home page banner, high impact, learning, and who we are images from drive
