### ISSUE TITLE
Update/replace banner image on "Application Process"

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#204]
Need to identify a photo. cc @Dahianna @danielaaburtotc

**Comment by Dahianna** [comment]
Use image we are using for social media preview @jaredbain and @danielaaburtotc

**Comment by Dahianna** [comment]
@danielaaburtotc will resize [this pic](https://drive.google.com/file/d/1MefxTGS-ecxjUl47lMHTK7xn50kqfE1O/view?usp=sharing) to use as banner

**Comment by Dahianna** [comment]
Daniela sent to Jared. Jared will update once Ruby is done.

**Comment by danielaaburtotc** [comment]
@jaredbain Here are the links to both cohort preview images:
2023 cohort: https://drive.google.com/drive/folders/1bucnPYcdz5Wf7vyGM-rXMvz_EgmpDrrr?usp=drive_link
2022 cohort: https://drive.google.com/drive/folders/1yBWosBF80AV5afxHZbqcO_y513c4GLEj?usp=drive_link

**Comment by chriskuang4** [comment]
@danielaaburtotc to add link to banner image. TY!

**Comment by danielaaburtotc** [comment]
[Here](https://drive.google.com/file/d/19Cg1XFChBwY7LIC9eMcPOqT5Y59aB6_6/view?usp=drive_link) is the link to the image!
