### ISSUE TITLE
Certain press card images are distorted 

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#213]
## Describe the bug

Images for the press section at the bottom of the home page are different sizes, resulting in distortion. See attached screenshots for an example.

## Expected behavior
Instead of resizing images to fit in the box, we could try cropping to size, which maintains the aspect ratio.

## Screenshots or other reference materials
Screenshot (horizontally compressed): 
![Screen Shot 2022-09-29 at 11 19 56 AM](https://user-images.githubusercontent.com/85581929/193072428-3409c5ae-f414-4960-8e03-8d63651c2144.png)

Original image/ratio:
![2022-FT-Influencer List-Hero](https://user-images.githubusercontent.com/85581929/193072954-74fb706c-bc81-40b4-a88d-d7cb26730a63.jpg)

**Comment by Dahianna** [comment]
Section no longer exists on site. Disregard
