### ISSUE TITLE
Fix nav bar spacing for medium width screens

### ISSUE THREAD

**Issue by jaredbain** [GSA/digitalcorps.gsa.gov#237]
When screen size is between tablet and desktop size, the nav bar gets compacted and is not visually appealing.

**Comment by Dahianna** [comment]
@jaredbain working on a two-tier navigation branch. Will show example next week

**Comment by Dahianna** [comment]
For future reference: We can condense the FAQ and process sections under application or we can reduce the font size and make it not all caps

**Comment by jaredbain** [comment]
Two Tier nav bar nearing completion. CSS is about 95% complete

**Comment by Dahianna** [comment]
Fixing burger version 
Deadline: 2/17/23

**Comment by chriskuang4** [comment]
Still running into USWDS issues - Jared will reach out in #uswds and/or #uswds-public. 

In parallel, Jared will share a staging link for the hover menu (whereby Application Process and FAQ are removed from the main bar, and will appear upon hover of the Apply button). Exploration needs to be done how hover effect would work on mobile.

**Comment by Dahianna** [comment]
Preview for two rows: https://federalist-ab979a96-fca9-4c8a-a85e-18500f030448.sites.pages.cloud.gov/preview/gsa/digitalcorps.gsa.gov/nav_bar/

**Comment by chriskuang4** [comment]
Jared shared staging link today for two-tiered nav bar. This would fix the medium size screen bug, but be pushed to all screen sizes.

JB will start today on the hover/dropdown from the apply button (3 options: application process, FAQ, apply now) - estimated time for staging is tomorrow 3/1.

Waiting to make a decision on path forward until that second staging link is ready.

**Comment by chriskuang4** [comment]
15 people using tablets out of ~3000 (in the last month): 0.5%. 

Resolutions impacted: 1120 x 836. Roughly 1% impacted.

**Comment by Dahianna** [comment]
Dropdown mockup deadline: 3/8

**Comment by Dahianna** [comment]
Looks good just some small edits:

- Create more space between down arrow and "apply"
-  On mobile, APPLY is in all caps

**Comment by jaredbain** [comment]
Waiting for PR to be approved and then will push to live site.
