### ISSUE TITLE
fix pages.cloud.gov build

### ISSUE THREAD

**Issue by DaveSkender** [GSA/digitalcorps.gsa.gov#246]
## Describe the bug

After updating the webhook [per instructions](https://gsa-tts.slack.com/archives/C02KXM98G/p1670955691148269) to the new pages.cloud.gov build it no longer auto-triggers a build on both Pull Request or `main` post-merge deploy.  @drewbo, @jaredbain 

Example: https://github.com/GSA/digitalcorps.gsa.gov/pull/177 and https://github.com/GSA/digitalcorps.gsa.gov/commit/a6f747ae89f0d3e0a2576016c7cef68aadee743a

**Comment by DaveSkender** [comment]
@jbbain I suspect we already fixed this one.

**Comment by jaredbain** [comment]
Yes this was fixed. We can close this issue.
