### ISSUE TITLE
Create "case study pages" for cohort 1 projects

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#250]
Similar to https://presidentialinnovationfellows.gov/projects/cdc-analytics-and-interoperable-systems/ we want to create project pages to showcase the challenge, solution, and impact of the projects Fellows are working on

To do
- Create design and implement
- Create content
- Get content approved by partners
- Add content to pages

**Comment by Dahianna** [comment]
@jaredbain recoding so it's easier to add new content.

**Comment by jaredbain** [comment]
Recoding completed. Next steps is reviewing the Individual Project Page designs and working on the coding the pages.

**Comment by Dahianna** [comment]
Thinking of repurposing either Fellows page or blog post design. Daniela will provide concepts once contract is figures out.
Deadline: 2/24 for concept decision

**Comment by Dahianna** [comment]
Waiting on renewing designer contract

**Comment by Dahianna** [comment]
[Content ](https://docs.google.com/spreadsheets/d/1iM8CHAeMp9GsnKmSiDz0ssRuRPqJCuPo5fMDAUmrbpI/edit#gid=0)under review before adding to the site

**Comment by Dahianna** [comment]
@jaredbain will update branch with new designs. @chriskuang4 and @Dahianna will work on finalizing content

**Comment by jaredbain** [comment]
Working on mobile view for individual pages

**Comment by jaredbain** [comment]
Mobile and tablet view for individual project pages completed. Working on javascript for new filters and styling for new project cards on project page

**Comment by Dahianna** [comment]
Updates to project page/case study @jaredbain 

- [ ] Reduce height of banner
- [ ] Sentence case for headers and skill sets
- [ ] Remove space between first skill and comma
- [ ] Match sidebar and header capitalization
- [ ] Match About in sidebar to be About [agency name]

**Comment by Dahianna** [comment]
Content: https://docs.google.com/spreadsheets/d/1iM8CHAeMp9GsnKmSiDz0ssRuRPqJCuPo5fMDAUmrbpI/edit#gid=0
