### ISSUE TITLE
Add 2023 Fellows

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#251]
- Add year filter
- Add Fellows bios and photos

**Comment by Dahianna** [comment]
Content: https://docs.google.com/spreadsheets/d/1UEKppC7W671a-5cF-fbGmn1f0BVhObl7puiY2xMTsVI/edit#gid=501612640

**Comment by chriskuang4** [comment]
@jaredbain to create a private branch and pre-load empty pages for each fellow.

**Comment by Dahianna** [comment]
Preview: https://federalist-ab979a96-fca9-4c8a-a85e-18500f030448.sites.pages.cloud.gov/preview/gsa/digitalcorps.gsa.gov/2023_fellows/fellows/
