### ISSUE TITLE
Add disclaimer to news section

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#259]
OSC and OGC have requested we add a disclaimer to our news section to the following:

Finally, I'd also advise putting a disclaimer there saying that we periodically check links, but are only responsible for links to GSA materials. We are not responsible if the link to the non-GSA website no longer exists.

**Comment by Dahianna** [comment]
Since the outlet we interviewed with recently had requested to be added to our news section, it was brought up to OSC and OGC attention and we were able to come to this agreement. @chriskuang4

**Comment by Dahianna** [comment]
Let's prioritize this for next week

**Comment by Dahianna** [comment]
Jared will create previews to see where to place disclaimer
Deadline: 2/24/23

**Comment by chriskuang4** [comment]
Closing this issue.
