### ISSUE TITLE
Create branch to add new agencies to projects page

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#266]
Add these new agencies to projects landing page

**Comment by Dahianna** [comment]
Adding updates on this spreadsheet: https://docs.google.com/spreadsheets/d/18HMMDUzL_d1dp4LaWtrkXmCkjHXpp1m525D32nkDnTM/edit#gid=799871743

**Comment by Dahianna** [comment]
@jaredbain feel free to start work on a private branch. Thanks!

**Comment by chriskuang4** [comment]
Daniela mocking up two design options:

- One card per agency (whole width) with expandable project links?
- One card per project w/ impact area icons (and agency logo grid filter?)

**Comment by Dahianna** [comment]
**For v1 landing project section:**
-  will keep cybersecurity as both an impact area and track
- move learn more links to individual project page

**For v1 of the individual project pages**
- Move impact areas above skill sets 
- Add lear more link under logo
- Add fellow face(s) next to logo
- Fix menu to be more like application process one 
- Add texture/color on banner
- Create "similar projects" section to the bottom based on impact areas

cc @danielaaburtotc

**Comment by Dahianna** [comment]
Quick updates: Make Fellows face clickable to take to Fellow's page

**Comment by Dahianna** [comment]
@jaredbain can you link the branch to this issue?

**Comment by jaredbain** [comment]
The branch is now linked with this issue and issue #250

**Comment by Dahianna** [comment]
New agencies have been added to branch. Will close and use #258 for the rest of the updates
