### ISSUE TITLE
Add OSTP to projects page and update Meredith

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#272]
Add OSTP to agencies page. Meredith to provide content

**Comment by Dahianna** [comment]
@danielaaburtotc to provide logo by 5/19/23

**Comment by Dahianna** [comment]
@Dahianna to follow up with Meredith on content

**Comment by Dahianna** [comment]
Followed up with Meredith on 5/23. Waiting for her content

**Comment by chriskuang4** [comment]
Closing this out.
