### ISSUE TITLE
Update projects landing page: Make all cards project cards

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#281]
https://docs.google.com/spreadsheets/d/18HMMDUzL_d1dp4LaWtrkXmCkjHXpp1m525D32nkDnTM/edit#gid=799871743

**Comment by Dahianna** [comment]
@jaredbain I've added the first draft of the agency blurb. Feel free to use this to start creating content in the branch. We'll love to see it at the next sync. Thanks!

**Comment by Dahianna** [comment]
@jaredbain for phase 1 of project page updates:

- [ ] Remove video and update with random glass building image
- [ ] Add Filters column
- [ ] Update java script and css on cards
- [ ] Add agencies banner
- [ ] Update title so it doesn't say "Inaugural Host Agencies"

**Comment by Dahianna** [comment]
Preview: https://federalist-ab979a96-fca9-4c8a-a85e-18500f030448.sites.pages.cloud.gov/preview/gsa/digitalcorps.gsa.gov/update_projects_page/projects/

**Comment by Dahianna** [comment]
Make all the cards “project cards” (currently they are “agency cards”)

- Update the filters @jaredbain 
-  Break out 2022 agency cards to project cards @Dahianna 
- Add [2023 project cards] @jaredbain (https://docs.google.com/spreadsheets/d/18HMMDUzL_d1dp4LaWtrkXmCkjHXpp1m525D32nkDnTM/edit#gid=799871743)
- Emily following up with agencies who haven’t approved

**Comment by chriskuang4** [comment]
To-dos

- [ ] styling
- [ ] make filters work
- [ ] spacing between the buttons and the text in the filters
- [ ] spacing between the top cards and the agency logo section
- [ ] Bold card titles
- [ ] Remove extra space between skill sets and commas, and unbold skill sets
- [ ] Eliminate "Inaugural Host agencies" header and also the first sentence "Fellows work alongside ... and public experience."
- [ ] Move remaining sentence "If you are a federal employee ... reach out to us at usdigitalcorps@gsa.gov" into the agency logo banner under the logos and add a header above the logos "Agencies We Partner With" 
- [ ] Grey banner section will be seamless from the glass building header
- [ ] Update background color for "open science" impact area
- [ ] Make agency logos 2 rows of 9 each. and give each slight padding
- [ ] Remove extra period above filters on the left

**Comment by chriskuang4** [comment]
Styling expected Friday
JavaScript/filters expected Monday

**Comment by Dahianna** [comment]
- Look into collapsing filter on mobile (@jaredbain )
- Under agency filter align long agency names (@jaredbain)
