### ISSUE TITLE
Add agency-facing subpage under "Projects" tab

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#307]
## Describe the solution you'd like

I'd like federal agency employees to have a page where they can see more details about hosting a U.S. Digital Corps Fellow, similar to https://login.gov/partners/ or https://presidentialinnovationfellows.gov/agencies/.

It could have our latest timeline for engagement, traits of successful host agencies, information from our agency one-pager, and other details. 

It would be very valuable from a BD perspective to have a place for inbound interest and a URL that is sharable.

**Comment by chriskuang4** [comment]
@chriskuang4 to think about this in the scope of our call for 2024 partners.

**Comment by Dahianna** [comment]
Moving to #564
