### ISSUE TITLE
Have more specific social media preview images

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#313]
Fellows: Feel free to start working on these issues by assigning them to yourself. If you have any questions feel free to add it in the comments and tag @jaredbain and @Dahianna. Also always create a new branch and add Jared as reviewer.
Skills: Design

Right now, links to most of the site pages all load the generic "build a brighter future" image card, which is nice but does not best reflect the more specific content of various links. We would like some images we could use to create better previews for these pages.

**Comment by chriskuang4** [comment]
@Dahianna to share links to Google Drive folders with photos -- need to replace stock photos with USDC photos

**Comment by jaredbain** [comment]
Created branch with social media preview images updated. Blog page still needs a photo.

**Comment by Dahianna** [comment]
Here's a folder with pictures we can use but have not asked folks for their permission. @chriskuang4 could you identify folks and reach out to get permission. Thanks! https://drive.google.com/drive/folders/1OMaKXN3YvVTOUppAwpFRC85ImRe6q6-Y

**Comment by chriskuang4** [comment]
Checked box = approved by all

- [x] BOS_Day1-1811 (Kathleen, Espy)
- [x] 8223-4 (Kristina, Nolan)
- [ ] 8223-21 (Bella, Jamie) -- pending both
- [x] 8223-22 (Laurel, Blake)
- [x] 8223-23 (Yaritza, Melissa)
- [ ] 8223-170 (Emily, Laurel, Samantha) -- pending Emily
- [x] 8223-255 (Kira)
- [x] 8223-pre-2 (Laurel)

**Comment by chriskuang4** [comment]
All of the above images have been approved; now to determine which ones match which pages.

**Comment by Dahianna** [comment]
Updated images: https://www.figma.com/file/fSWJArInk52IBK6I4vzx7N/Thumbnail-Assets-for-USDC?type=design&node-id=0%3A1&mode=design&t=Y9KM2Y4TdEN3vXFi-1
