### ISSUE TITLE
Standardize treatment/design of quotes in blog posts + impact stories

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#317]
This may lead to the creation of a standardized template for blog posts and impact stories that features common building blocks (headers, quote boxes, image formatting, etc).

In the meantime, the quote pullout in [this impact story](https://digitalcorps.gsa.gov/projects/acf-iprc/) is done simply in Markdown whereas [this blog post](https://digitalcorps.gsa.gov/blogs/building-and-supporting-a-diverse-technology-workforce-in-the-federal-government/) has a quote box at the top that looks like HTML. It'd be great to have consistency.

- [ ] Determine ideal quote style
- [ ] Add padding to "gray box" quote style
- [ ] Identify all quote usages on USDC website
- [ ] Work with Jared to implement style across all quotes on USDC website

**Comment by chriskuang4** [comment]
Would love to do some thinking on this before we publish more content and thus will have more to back-update if we do this later down the road.

**Comment by chriskuang4** [comment]
@danielaaburtotc prefers the "box" quote format here: https://digitalcorps.gsa.gov/blogs/building-and-supporting-a-diverse-technology-workforce-in-the-federal-government/

She will connect with Jared to make any fixes to existing content and ensure we are consistent moving forward.

**Comment by chriskuang4** [comment]
Here is a screenshot / image of a quote: https://digitalcorps.gsa.gov/blogs/resume-best-practices/

We will also have more padding on the gray box.

**Comment by jaredbain** [comment]
PR is ready or review
