### ISSUE TITLE
Add 2023 Fellow headshots

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#324]
@Dahianna should have the photos; @danielaaburtotc to format, and @jaredbain to update.

**Comment by Dahianna** [comment]
@danielaaburtotc here are the [Fellow photos](https://drive.google.com/drive/folders/1qsx5Ufl6SC8t9Pn1ZA-xPi7ov53n_L5H) ready for website editing. Could you also do it for the [PMO pics](https://drive.google.com/drive/folders/1qnkzapUn7mc62gPLi6c2DJfHLNmdqWpT), sometimes I need it for the newsletter. Thanks!

**Comment by chriskuang4** [comment]
On @danielaaburtotc's list for today -- will shared with Jared once complete.

**Comment by chriskuang4** [comment]
Here is the link to the spreadsheet: https://docs.google.com/spreadsheets/d/1UEKppC7W671a-5cF-fbGmn1f0BVhObl7puiY2xMTsVI/edit#gid=501612640

@jaredbain going to start working on these. 
@chriskuang4 to track down missing photos for:

- Alyssa Bell
- Drew Keller
- Yuqing Zhou

**Comment by chriskuang4** [comment]
Replacing these is in motion; just a few left. @jaredbain will create pull request after. ETA Wed 10/11/23.
