### ISSUE TITLE
Social media preview for blog posts and blog

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#356]
Add images used in the blog post card on blog landing page as social media previews too

**Comment by Dahianna** [comment]
- @danielaaburtotc Create an image for the blog preview
-  @jaredbain Make the blog posts card the social media previews

**Comment by chriskuang4** [comment]
@danielaaburtotc looking for a social media preview image for https://digitalcorps.gsa.gov/blog/

@jaredbain will make the social media preview image for specific blog posts the image in the blog homepage.

**Comment by chriskuang4** [comment]
Daniela has the preview image created; she will share in our #usdc-digital-strategy Slack channel for feedback and discussion.
