### ISSUE TITLE
X-post gsa.gov forthcoming blog post (11/1)

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#363]
We'll need a branch prepared for a new blog post to go live 10/30.

**Comment by Dahianna** [comment]
@Dahianna will do this

**Comment by Dahianna** [comment]
@jaredbain ready for you to fix my issues. Thank you! https://github.com/GSA/digitalcorps.gsa.gov/pull/386

**Comment by jaredbain** [comment]
@Dahianna all fixed. I'll go ahead and merge it.
