### ISSUE TITLE
Close applications 11/17

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#391]
-Switch config file from true to false to hide tracks
- Remove banner
- Update process page and apply pages to say "2204 applications are now closed..."

**Comment by Dahianna** [comment]
@jaredbain to create branch

**Comment by jaredbain** [comment]
Created branch to close applications. 
Can view the staging link here:
https://federalist-ab979a96-fca9-4c8a-a85e-18500f030448.sites.pages.cloud.gov/preview/gsa/digitalcorps.gsa.gov/close_applications/
