### ISSUE TITLE
Add more about impact / projects. / link on the home page

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#401]
Should we update the homepage to link to impact stories, blog post, and any page that gets a lot of traffic? Now that we have more impact stories and details about projects -- we shjould link there somewhere from our homepage.

**Comment by Dahianna** [comment]
@Dahianna to look at traffic data

**Comment by Dahianna** [comment]
This was implemented by #462 and #526
