### ISSUE TITLE
Update Alyssa Bell headshot

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#404]
@Dahianna -- can you please get the final headshot file for Alyssa Bell from the photographer and share with her? She selected **1X8A9846**. We can look out in Slack DM to see if she wants us to update the photo on the website.

**Comment by Dahianna** [comment]
Picture sent to Alyssa on 1/2/24. @danielaaburtotc in case Alyssa wants her pic updated on the site can we work on creating a site version for it. Thanks! https://drive.google.com/file/d/1CgBsJqihhl_aVSCxda2riF5k3nqt-OhY/view?usp=drive_link
