### ISSUE TITLE
Check social media preview images work on both LinkedIn and Twitter

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#412]
Some pages don't show the right preview on LinkedIn. For example this how the preview works for the project page:

Twitter

![Screenshot 2024-01-02 at 1 48 59 PM](https://github.com/GSA/digitalcorps.gsa.gov/assets/22921144/f80ecdaa-a3b5-4d90-9d87-f10fba088f98)

LinkedIn
![Screenshot 2024-01-02 at 1 49 19 PM](https://github.com/GSA/digitalcorps.gsa.gov/assets/22921144/a0d82fdd-ca35-446b-a3a0-7779b3908e72)

Let's make sure the right preview image appears on both LinkedIn and Twitter. This doesn't seem to be an issue for the apply page.

**Comment by Dahianna** [comment]
Good job all done!
