### ISSUE TITLE
AMP January results

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#432]
Review AMP results and implement recommendations. A passing grade is 88% and we are 86%.  https://docs.google.com/spreadsheets/d/1iHydCz_avL06iXta-aGGvj_h3j1aiktPnWoDAXcJJlk/edit?pli=1#gid=1103782849

**Comment by chriskuang4** [comment]
Asked for clarification in #digital-council about where we got dinged, and also looks like we are affected by it scanning all of GSA.gov and not just our subdomain.

https://gsa-tts.slack.com/archives/CMGHQPSLC/p1709059885232039?thread_ts=1707420994.157349&cid=CMGHQPSLC

**Comment by Dahianna** [comment]
Waiting on the AMP team to rescan. Will update once we have the new data.

**Comment by Dahianna** [comment]
New scan coming end of March

**Comment by Dahianna** [comment]
We'll close this issue and create a new one if necessary
