### ISSUE TITLE
Review process page for accuracy

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#447]
**Apply**
- [x] Add sentence about 2025 cohort applications coming this Fall @Dahianna 

**Application process**
- [x] Update with statement showing the content might change before applications open
https://digitalcorps.gsa.gov/process/ @jaredbain 
- [x] Add sentence about 2025 cohort applications coming this Fall @Dahianna 
Update the following with the correct dates:
- [x] You meet the eligibility requirements for the Pathways Recent Graduates program (currently enrolled students must graduate by DATE to be eligible)
- [x] You are a recent graduate who has received an associates, bachelors, masters, professional, doctorate degree or certificate from a [qualifying educational institution](https://ope.ed.gov/dapip/#/home) within the past two years DATEUp
- [x] Add data science eligibility
- [x] Update dashes for the months drop down sections
- [x] Update e‑QIP to eApp
- [x] Remove extra a in USAaccess
- [x] Add "GSA HR will also send instructions for requesting an official final transcript from your school." to the end of the first paragraph in the March-July box
- [x] Add "Once your eApp has been initially cleared and your final transcript received, a GSA HR specialist..."

**FAQ**

- [x] Update second question about salary and location with correct pay table and salary example
- [x] Ask Emily if we have new questions
- [x] Add one about speaking to current fellow: come to info sessions otherwise we can't do due to bandwith
- [x] Add one about administration change impact: No change gov wide support not based on administration
- [x] Add do we have internships question: No, point to usajobs intern page and other non-profit orgs

**Comment by chriskuang4** [comment]
[] Add "GSA HR will also send instructions for requesting an official final transcript from your school." to the end of the first paragraph in the March-July box
[] Add "Once your eApp has been initially cleared and your final transcript received, a GSA HR specialist..."

**Comment by Dahianna** [comment]
@chriskuang4 once you've reviewed and approved we can publish the updates and merge

**Comment by Dahianna** [comment]
@jaredbain all updates are in this doc: https://docs.google.com/document/d/18fiuOIdyTAbmXxSdevYviyNbBv15hcaRakJ80J4mU1w/edit#heading=h.hz5xm8qxtf67
