### ISSUE TITLE
Home page updates

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#450]
Remove Image with overlay texts and add boxes that link to Fellows and impact pages. Similar to the opportunity and who we are boxes already there.

**Comment by Dahianna** [comment]
@jaredbain Let's use [this one ](https://drive.google.com/file/d/1Odb8-FY-1TLCgHlSLDb5ZIHMcLwxWkio/view?usp=drive_link)for the Fellows section with "Find out more about our Fellows" as the tagline.

And let's use this one for [projects](https://drive.google.com/file/d/1_h6aYPZGvQ0dZGKIPJ82mygpP_-CTa_P/view?usp=drive_link) with the tagline "Make a difference for the American public".

**Comment by Dahianna** [comment]
Once you're done feel free to tag @chriskuang4 for his review

**Comment by jaredbain** [comment]
PR is ready for review @chriskuang4
