### ISSUE TITLE
Fellows page updates

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#452]
- [x] Remove https://digitalcorps.gsa.gov/fellows/olivia-haring/ @jaredbain 

Update agency:

- [x] Lacy Kelly Ramos: remove agency @Dahianna 

- [x] Selyne: Update to GSA @Dahianna 

- [x] Joe L: Remove agency @Dahianna  

- [x] Rasheem: Add ACF @Dahianna

**Comment by Dahianna** [comment]
@jaredbain I reopened because we still need to remove Olivia, unless you did that already

**Comment by jaredbain** [comment]
@Dahianna I created a pull request to remove her from the site. Its ready for review and approval.
