### ISSUE TITLE
Events section

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#461]
- Add events header under banner in apply page
- Sentence "upcoming virtual and in-person events. If you want USDC at your event email
- Add events as bullet points: Name, Date(s), link
- After events add a sentence about "if can't make event, check video and subscribe to our newsletter to get notified of new events.

**Comment by Dahianna** [comment]
@jaredbain this is ready for your review

**Comment by Dahianna** [comment]
@daniela-aburto let me know if you have any design recommendations for this section.

**Comment by Dahianna** [comment]
@jaredbain has everything he needs and can implement after package update.

**Comment by Dahianna** [comment]
@jaredbain will implement 
- University of Virginia PIT Career Fair (Sept 3, 2024; Charlottesville, VA)https://career.virginia.edu/tech-night-takeover-public-interest-technology-university-network-fair
- 2024 National HBCU Week Conference (Sept 18-19, Philadelphia, PA) https://sites.ed.gov/whhbcu/2024-annual-national-hbcu-week-conference/ 
- UMD Campus Career Fair (Sep 24, 2024 - College Park, MD): https://careers.umd.edu/who-we-help/employers/recruit-hire-terps/career-fairs-industry-events/2024-fall-career-internship
-  The National Cybersecurity Virtual Career Fair (Friday, September 27th from 12pm - 4pm EST.): https://caecommunity.6connex.com/event/virtual/students/login

**Comment by jaredbain** [comment]
We will be using the calendar display component from USWDS https://designsystem.digital.gov/components/collection/

**Comment by Dahianna** [comment]
@dahianan provide event descriptions to Jared
