### ISSUE TITLE
2024 Fellows bios

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#476]
Create a branch to start adding Fellows content to the site

- [x] Provide @daniela-aburto with photos 
- [x] @Dahianna to work with Dany to standardize content
- [x] @jaredbain will create branch and update as needed

**Comment by Dahianna** [comment]
@daniela-aburto here's the first round of photos https://drive.google.com/drive/folders/1q4cOEFUTxiiCnM9R0_RD6CWsB3QYTu5az-dbDa48XSK8IVGyQdfQOD9jkC4vkV-FOK09TLdC

**Comment by Dahianna** [comment]
Dany reviewed first 10 here: https://docs.google.com/spreadsheets/d/1prvxwzaVbTC1nLaxu5nn0sl_F_VRhE3Ivv12WnqGMgI/edit?gid=1707885437#gid=1707885437

Dahianna reviewing and then tagging @jaredbain 

@daniela-aburto will have photos ready by end of week

**Comment by Dahianna** [comment]
- @Dahianna to create tag lines
- @daniela-aburto will work on site photos

We are keeping all Fellows in the Fellows page

**Comment by Dahianna** [comment]
@jaredbain can we double check all agency info is correct. Thanks!

**Comment by Dahianna** [comment]
And ensure "and" in data science and analytics

**Comment by jaredbain** [comment]
Updated "and" in all 2024 data science and analytics fellows

**Comment by jaredbain** [comment]
When creating a file for new fellows, if the fellow does not have a bio profile pic, you can leave the image section blank. The site will autopopulate the default blank image for them. 
<img width="501" alt="Screenshot 2024-07-31 at 1 49 50 PM" src="https://github.com/user-attachments/assets/9ad6d9bf-46ab-46b4-bdbd-ac2185b9657b">

If a fellow has a picture, the proper format would be (firstName-lastName-headshot.webp). you can look at other fellows as an example. Please place their photos in the folder path, [/assets/images/fellows/2024/](https://github.com/GSA/digitalcorps.gsa.gov/tree/2024-fellows-cohort/assets/images/fellows/2024)


For fellow's social media meta images, the code should be 
social_image: /assets/images/social/fellows/social-firstName-lastName.webp
Place those photos in the folder [here](https://github.com/GSA/digitalcorps.gsa.gov/tree/2024-fellows-cohort/assets/images/social/fellows)
