### ISSUE TITLE
2024 Fellow clean ups

### ISSUE THREAD

**Issue by chriskuang4** [GSA/digitalcorps.gsa.gov#496]
- [x] Angela Chang - add comma for education: **University of California, Berkeley** (check for consistency); also **Brian Xi, Claira Kauffmann, Derek Wang (UCLA), Prakash Krishnan**
- [x] Branda Ayo - add period at end of her quote
- [x] Brianna Carnagie - change quote to say Center**s** for Medicare and Medicaid Services
- [x] Bryan Pablo -- change to "he regularly attended hackathons on weekends, where he connected with other students and developed software..."
- [x] Christina Andrade -- change to "her new chapter as a U.S. Digital Corps Fellow" ; her quote to "USDC immediately appealed..." (not The USDC) ; and fun fact to "thanks to a U.S. State Department cultural... "
- [x] Colton Lapp change quote to "It's tasked with..., and when it fails to deliver..." and spell out "eight" and "two" in his fun fact, add periods between "U.S." and add a period at the end.
- [x] Danahue Davidson: remove the Agency tag for now, add a comma between Atlanta, GA, and change quote to "Opportunity, collaboration, and growth."
- [x] Elise Lambkin - capitalize Fellow in her quote, update to "product manager" in the tag
- [x] Ella Grady - change "young" to "early-career" in her quote and correct spelling of "Digital Corps"
- [x] Ellis Obrien - remove "the" in "the USDC" in his quote
- [x] Emma Gray - make consistent "University of Illinois Chicago" between the bio and the sidebar; add oxford comma in last sentence of first paragraph; add "**and** make pasta from scratch" removing "etc" from second paragraph
- [x] Gregg Rich - add periods between "U.S. Fish and Wildlife Service" as well as in the second paragraph; change first sentence to be "both in the U.S. and overseas in Paraguay, where he also served as a Peace Corps Volunteer..."; remove "had" from next sentence; remove "the" from "the USDC" in his quote; add period to fun fact.
- [x] Jenny Park -- "a little bit of colloquial" seems like a hanging phrase?
- [x] Jock Croft - change "were" to "was" in the first sentence
- [x] Johan Ortega-Rios - make consistent UIUC styling in bio and sidebar
- [x] Joseph Helbing - add "career transition and **is** new to data science" and remove "the" from "the USDC"
- [x] Josey Benandi - consistency of Georgia Tech in sidebar with others (Georgia Institute of Technology)
- [x] Keri Alford - remove "Fellows program" from quote and capitalize "Fellows"
- [x] Kyle Psilopoulos - remove "the" from "the USDC" in quote and change "their" to "its"
- [x] Kylie Hunter - change bio to "As a solutions engineer at Salesforce, Kylie leveraged..." ; spell out "five" in fun fact
- [x] Lisette Solis - add periods between "U.S." and change spelling to "traveling" 
- [x] Maggie Sullivan - remove "the" from "The USDC" in quote; add period to fun fact
- [x] Mark Aronson - capitalize "Fellow" in quote
- [x] Michael Whitaker - remove apostrophe in first paragraph; remove "the" from "the USDC"
- [x] Mohammad Ghaznavi - change "their" to "its" in quote
- [x] Nicholas Sura - remove "the" from "the USDC" and add apostrophe to "nation's"
- [x] Olivia Athelus - should her education be past tense? "received her Master's degree..."? Change quote to "I joined USDC because..."
- [x] Prakash Krishnan - add period to fun fact
- [x] Sam Levy - add periods to "U.S." in bio and capitalize Supreme Court in fun fact
- [x] Sunny Chen - her track is "Product_Management"?
- [x] Taylor Miller - change last bio sentence to "reading, and traveling, and is always...."
- [x] Tyler Celestin - add period to fun fact
- [x] Younes Brahimi - change spelling to "Honors"
- [x] Zach Palmer - remove "the" from "the USDC" in quote
- [x] Zoya Egiazaryan - add "program" to first sentence "Human-Computer Interaction program"
- [x] Zïa Maldonado -- in fun fact, add ï to her name, capitalize AI, and fingertips is one word
- [x] Make sure blurbs under photos are consistent (ie some have periods like Zobair, and others don't)

**Comment by Dahianna** [comment]
@chriskuang4 it seems we've used both `Masters of/in` and `Master of/in`. The correct form [seems to be ](https://www.grammarly.com/blog/masters-degree/#:~:text=The%20correct%20way%20to%20spell,apply%20to%20a%20bachelor's%20degree.)`Master of/in'. Do you want me to update all to that?
