### ISSUE TITLE
Support multiple filters on the fellows page 

### ISSUE THREAD

**Issue by ghost** [GSA/digitalcorps.gsa.gov#513]
## Is your feature request related to a problem? Please describe

Fellows have requested that the selection of multiple fellows be supported. This would allow a more granular view of which fellows are at particular agencies in a specific track or year. 
 
## Describe the solution you'd like

We would change the fellows collection to be in the following format (all files not included for simplicity): 
```
└───fellows
    └───2024
         ACF.html // year + agency filter 
         Sofware_Engineering.html // year + track filter 
        └───Software_Engineering
            └───ACF.html // year + track + agency filter 
    └───Software_Engineering
         └───ACF.html // track + agency filter 
    ACF.html // agency filter 
    2024.html // year filter 
    Software_Engineering.html // track filter 
```

We would then make changes to `filter.js` and `fellows-filters.html` to ensure that the correct urls are generated and that we allows the selection of multiple filters at a time.

**Comment by samlevy3** [comment]
This change would also add a script to automatically generate the `/fellows` directory and appropriate sub-directories/page definitions based on the `/_data` file constants. This would simplify the additions of new agencies/tracks/years.
