### ISSUE TITLE
Incorrectly Tagged Fellows

### ISSUE THREAD

**Issue by samlevy3** [GSA/digitalcorps.gsa.gov#515]
## Describe the bug

Some of the fellows are incorrectly tagged causing them to show up under the wrong agency filter (or not show up at all) 

- Thalia is tagged under `DOC` but should be tagged under `IRS`
- It looks like there was a change from `DOS` -> `State` but none of the 2022/2023 fellows were updated to match the new tag. 

## To Reproduce

1. Go to https://digitalcorps.gsa.gov/fellows/State (none of the 2022/2023 Department of State fellows show up) 
2. Go to https://digitalcorps.gsa.gov/fellows/IRS/ (Thalia does not show up) 

## Expected behavior

1. 2022/2023 fellows should appear when the Department of State filter is selected. 
2. Thalia should appear when the IRS is selected

**Comment by Dahianna** [comment]
Thanks for this fix Sam! We'll merge soon
