### ISSUE TITLE
Update Fellows photos with Gov headshots

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#543]
Melissa will format photos for website

**Comment by Dahianna** [comment]
Some of the pics had coloration issues will update with new ones in the folder and let Melissa know when they are ready for formatting

**Comment by Dahianna** [comment]
Dahianna shared updated files with Melissa to start formatting

**Comment by Dahianna** [comment]
@Dahianna provided @jaredbain with the headshots to create a branch for review

**Comment by jaredbain** [comment]
Some headshots I was unable to determine which Fellow they belong to, need assistance in identifying. The headshot file names are listed as 

- Headshots_10.24-06.png
- Headshots_10.24-09.png
- Headshots_10.24-14.png
- Headshots_10.24-17.png
- Headshots_10.24-28.png
- Headshots_10.24-29.png
- Headshots_10.24-34.png
- Headshots_10.24-38.png
- Headshots_10.24-44.png
- Headshots_10.24-59.png
- Headshots_10.24-60.png
- Headshots_10.24-61.png
- Headshots_10.24-62.png
- Headshots_10.24-63.png
- Headshots_10.24-66.png

**Comment by Dahianna** [comment]
@jaredbain can you change Eleanor Kate Habich pic back to the non-gov photo? Thanks!
