### ISSUE TITLE
Agency page

### ISSUE THREAD

**Issue by Dahianna** [GSA/digitalcorps.gsa.gov#564]
Agency-facing page on website as subpage under "Projects" tab

@jaredbain  If we had a Google Doc of content for a new page (call it /agencies...?), how long would it take to spin it up, including any design? We'd probably keep it fairly barebones design-wise.

**Comment by jaredbain** [comment]
It can be fairly easy to make, it's usually the CSS that takes most of the time. But if it's barebones design-wise, it shouldn't be a hassle and ready within a couple days.

**Comment by Dahianna** [comment]
@jaredbain here's the content: https://docs.google.com/document/d/1w-NTeGQo3jFxZIFvbTz1PoLVKuWjETaz8JqNsUxUWj0/edit?tab=t.0

**Comment by Dahianna** [comment]
12/13/24 updates

- [ ] Update banner to say "For Agencies
- [ ] Add a sentence to include the partnerships email in the first paragraph
- [ ] Remove mentions of "emerging tech"
- [ ] Move project and impact link to the body
- [ ] Link to a source that explains SME-QA
