### ISSUE TITLE
Feature Press Articles

### ISSUE THREAD

**Issue by mvdanilova** [GSA/digitalcorps.gsa.gov#82]
Dahianna & leads to align press highlights (articles and multimedia) and incorporate on page. Similar to the usds.gov "USDS in the news" section on [their homepage](https://www.usds.gov/)

**Comment by mvdanilova** [comment]
Dahianna & leads to align press highlights (articles and multimedia) and incorporate on page

**Comment by chriskuang4** [comment]
+ USDC press releases, consider how we can also incorporate social media

**Comment by chriskuang4** [comment]
@jaredbain per our discussion yesterday, please share with @Dahianna and I a spreadsheet with the structure + fields that you need from us to populate the tracker. A few other questions -- will be endless scroll, or will we be capped at X links?

And circling back on the question of whether it's possible for us to "pin" X number of articles to always show up first, regardless of chronological order?

**Comment by jaredbain** [comment]
Yeah, I'll have a spreadsheet template for the structures by COB. For now, it can be endless scroll if you prefer, but after too many articles we may want to cap it.  It may be possible for us to pin X number of articles to always show up first, just need to do some research.

**Comment by chriskuang4** [comment]
- Take off date for the design // @danielaaburtotc to work on a mockup.
- 
- [Spreadsheet for articles is here ](https://docs.google.com/spreadsheets/d/1SiWZY-CNI2x619jUqNbBfxKS5RheYjK6_Cz5Ef7p8ac/edit#gid=0)
