### ISSUE TITLE
Agency Projects Page

### ISSUE THREAD

**Issue by mvdanilova** [GSA/digitalcorps.gsa.gov#83]
Would like a "Projects" page in the main nav that would mimic that of PIF.gov/projects

**Comment by mvdanilova** [comment]
Would like a page mimic-ing https://presidentialinnovationfellows.gov/projects/

**Comment by Dahianna** [comment]
@chriskuang4 and @Dahianna will mockup some content for the page by 1/28/22

**Comment by Dahianna** [comment]
Working doc: https://docs.google.com/document/d/1dAkEitShPaWJv7whBl-Aa0je-CESmMsdoOE7XKBTYqc/edit

**Comment by chriskuang4** [comment]
@jaredbain @mvdanilova FYI that Dahianna and I have discussed wanting the project page link to be **digitalcorps.gsa.gov/projects/**
