### ISSUE TITLE
Add Blog functionality to website

### ISSUE THREAD

**Issue by mvdanilova** [GSA/digitalcorps.gsa.gov#84]
Blog to showcase content from USDC Fellows and leadership [guided by this proposal](https://docs.google.com/document/d/1b5nF3fOohypg4Zz3eBGkCUvujBexoyDCoJW0gYoIvBg/edit)

**Comment by jaredbain** [comment]
Revisit January 2023 based on changes to TTS digital strategy

**Comment by Dahianna** [comment]
@Dahianna will create a business case to present to the outreach director

**Comment by Dahianna** [comment]
[Business case ready ](https://docs.google.com/document/d/1b5nF3fOohypg4Zz3eBGkCUvujBexoyDCoJW0gYoIvBg/edit)for @chriskuang4  review to present to Outreach Director on Thursday

**Comment by Dahianna** [comment]
Next steps
- Wait for approval
-  No need for categories
-  Create tags (Be intentional about it)

**Comment by DaveSkender** [comment]
Consider https://www.netlifycms.org/ for the blog.
See [base cloud.gov pages template](https://github.com/cloud-gov/pages-uswds-jekyll) for setup.
It’s relatively easy to configure and use.

**Comment by Dahianna** [comment]
Star reviewed and provided feedback, sending to Ashley M for her review

**Comment by Dahianna** [comment]
Deadline: 2/28

**Comment by chriskuang4** [comment]
Updated ETA (Jared is also doing work w/ PIF ahead of their incoming cohort) on mockups: 3/9

**Comment by Dahianna** [comment]
Was Sprint 1 but now on hold

**Comment by Dahianna** [comment]
Soft approval received will start a branch to build

**Comment by Dahianna** [comment]
- Similar or most recent posts?
- Tags
-

**Comment by Dahianna** [comment]
@jaredbain created the branch with just basics. Will work on add cards and rest of design. Will complete by the end of 8/9 including individual blog pages.

**Comment by Dahianna** [comment]
Aiming to have branch with content to review by 8/11

**Comment by Dahianna** [comment]
@jaredbain Fixing some bugs that give 404 error when clicking the card to go to the post. Also working on styling

**Comment by Dahianna** [comment]
https://docs.google.com/spreadsheets/d/1SiWZY-CNI2x619jUqNbBfxKS5RheYjK6_Cz5Ef7p8ac/edit#gid=0 for content

**Comment by Dahianna** [comment]
Labels.tags: Announcement, tracks, agencies, and impact areas

**Comment by jaredbain** [comment]
Fixed individual page error, working on styling individual page template

**Comment by Dahianna** [comment]
@chriskuang4 and @jaredbain let's remove https://github.com/GSA/digitalcorps.gsa.gov/blob/new_blog_page/_blogs/us-digital-corps-marks-first-year-driving-impact-in-federal-technology.md since is not a blog post but a press release
