### ISSUE TITLE
Activate the Search Bar

### ISSUE THREAD

**Issue by mvdanilova** [GSA/digitalcorps.gsa.gov#85]
Turn back on

Estimated Completion: 2 days

**Comment by DaveSkender** [comment]
@jaredbain I just added you to the Search.gov site so you can administer settings, but please do a walkthrough with me as I recently added this to another site and can simplify your implementation when this comes up in priority.

For now, please do login at least once per 90 days as your account will expire.

**Comment by DaveSkender** [comment]
I'd done this recently with saferfederalworkforce.gov and remember needing to update a few things, here's some references as a good starting point:

- [page file](https://github.com/GSA/SaferFederalWorkforce.gov/blob/89a00fc29cd605a4f4a85683d2d61a2c743f0386/search/index.html)
- [include file](https://github.com/GSA/SaferFederalWorkforce.gov/blob/89a00fc29cd605a4f4a85683d2d61a2c743f0386/_includes/searchgov/form.html)
- [config info](https://github.com/GSA/SaferFederalWorkforce.gov/blob/89a00fc29cd605a4f4a85683d2d61a2c743f0386/_config.yml)

**Comment by chriskuang4** [comment]
@jaredbain hamburgering everything but the search bar for the medium-width page nav bar. Est. completion: Thu 11/3.
