### ISSUE TITLE
Left-align and add flag to official US Gov website header

### ISSUE THREAD

**Issue by chriskuangGSA** [GSA/digitalcorps.gsa.gov#9]
The "An official website of the United States government" header is centered and missing the flag icon, which appears inconsistent with [USWDS guidelines](https://designsystem.digital.gov/components/banner/), and how it appears on other sites (18F, PIF, TTS, USDS for example)

**Comment by DaveSkender** [comment]
Added flag, but keeping at center for review.

**Comment by DaveSkender** [comment]
Closing this issue, but can reopen if you want to see how the full left align looks.
